/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmUtama.java
 *
 * Created on 04 Des 13, 11:19:32
 */
package khanzahmsanjungan;

import fungsi.akses;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class HalamanDepan extends javax.swing.JFrame {
    private static HalamanDepan myInstance;
    private final sekuel Sequel=new sekuel();
    private final validasi Valid=new validasi();
    private String validasiregistrasi=Sequel.cariIsi("select set_validasi_registrasi.wajib_closing_kasir from set_validasi_registrasi");
        
    /** Creates new form frmUtama */
    public HalamanDepan() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(super.getClass().getResource("/picture/addressbook-edit24.png")).getImage());      
        //this.setSize(screen.width,screen.height);
    }    
   // private final Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new component.Panel();
        jLabel1 = new component.Label();
        jPanel3 = new component.Panel();
        jLabel3 = new component.Label();
        panel1 = new usu.widget.glass.PanelGlass();
        panel2 = new java.awt.Panel();
        btnPengunjungBaru = new widget.ButtonBig();
        btnDaftarPoliklinik = new widget.ButtonBig();
        btnDaftarBpjs = new widget.ButtonBig();
        btnBPJSFktp = new widget.ButtonBig();
        btnBPJSChekIn = new widget.ButtonBig();
        panel3 = new java.awt.Panel();
        LabelNomor = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::[ SIMRS KhanzaHMS, Sub Menu Anjungan Registrasi Mandiri Pasien ]::");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(130, 50, 130));
        jPanel1.setBorder(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 55));
        jPanel1.setLayout(new java.awt.BorderLayout(30, 0));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/SUltra48x48.png"))); // NOI18N
        jLabel1.setText("Anjungan Registrasi Mandiri Rumah Sakit Umum Daerah Rantauprapat");
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(10);
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 135));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(130, 50, 130));
        jPanel3.setBorder(null);
        jPanel3.setPreferredSize(new java.awt.Dimension(560, 30));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dikembangkan Oleh Khanza.Soft Media, Email : khanza_media@yahoo.com, Skype : khanza.media, HP : 08562675039");
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/wallpaper.jpg"))); // NOI18N
        panel1.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_LEFT_BOTTOM);
        panel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 1, 1, 1));
        panel1.setOpaque(true);
        panel1.setOpaqueImage(false);
        panel1.setPreferredSize(new java.awt.Dimension(200, 200));
        panel1.setRound(false);
        panel1.setLayout(new java.awt.BorderLayout());

        panel2.setBackground(new java.awt.Color(102, 102, 102));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(null);

        btnPengunjungBaru.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        btnPengunjungBaru.setForeground(new java.awt.Color(0, 0, 0));
        btnPengunjungBaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/gnome-searchtool.png"))); // NOI18N
        btnPengunjungBaru.setText("Ambil Antrian Loket");
        btnPengunjungBaru.setFocusable(false);
        btnPengunjungBaru.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPengunjungBaru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengunjungBaru.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPengunjungBaru.setIconTextGap(10);
        btnPengunjungBaru.setOpaque(true);
        btnPengunjungBaru.setPreferredSize(new java.awt.Dimension(200, 90));
        btnPengunjungBaru.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPengunjungBaru.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnPengunjungBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengunjungBaruActionPerformed(evt);
            }
        });
        panel2.add(btnPengunjungBaru);
        btnPengunjungBaru.setBounds(160, 20, 500, 50);

        btnDaftarPoliklinik.setBackground(new java.awt.Color(255, 204, 0));
        btnDaftarPoliklinik.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));
        btnDaftarPoliklinik.setForeground(new java.awt.Color(0, 0, 0));
        btnDaftarPoliklinik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/gnome-searchtool.png"))); // NOI18N
        btnDaftarPoliklinik.setText("Pasien Umum");
        btnDaftarPoliklinik.setDefaultCapable(false);
        btnDaftarPoliklinik.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDaftarPoliklinik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDaftarPoliklinik.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDaftarPoliklinik.setIconTextGap(10);
        btnDaftarPoliklinik.setOpaque(true);
        btnDaftarPoliklinik.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDaftarPoliklinik.setVerifyInputWhenFocusTarget(false);
        btnDaftarPoliklinik.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDaftarPoliklinik.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnDaftarPoliklinik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarPoliklinikActionPerformed(evt);
            }
        });
        panel2.add(btnDaftarPoliklinik);
        btnDaftarPoliklinik.setBounds(160, 90, 500, 50);

        btnDaftarBpjs.setBackground(new java.awt.Color(0, 255, 0));
        btnDaftarBpjs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));
        btnDaftarBpjs.setForeground(new java.awt.Color(0, 0, 0));
        btnDaftarBpjs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/gnome-searchtool.png"))); // NOI18N
        btnDaftarBpjs.setText("Surat Kontrol BPJS");
        btnDaftarBpjs.setDefaultCapable(false);
        btnDaftarBpjs.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDaftarBpjs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDaftarBpjs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDaftarBpjs.setIconTextGap(10);
        btnDaftarBpjs.setOpaque(true);
        btnDaftarBpjs.setPreferredSize(new java.awt.Dimension(200, 90));
        btnDaftarBpjs.setVerifyInputWhenFocusTarget(false);
        btnDaftarBpjs.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDaftarBpjs.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnDaftarBpjs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarBpjsActionPerformed(evt);
            }
        });
        panel2.add(btnDaftarBpjs);
        btnDaftarBpjs.setBounds(160, 160, 500, 50);

        btnBPJSFktp.setBackground(new java.awt.Color(0, 51, 204));
        btnBPJSFktp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));
        btnBPJSFktp.setForeground(new java.awt.Color(0, 0, 0));
        btnBPJSFktp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/gnome-searchtool.png"))); // NOI18N
        btnBPJSFktp.setText("Surat Rujukan Puskesmas");
        btnBPJSFktp.setDefaultCapable(false);
        btnBPJSFktp.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBPJSFktp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBPJSFktp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBPJSFktp.setIconTextGap(10);
        btnBPJSFktp.setOpaque(true);
        btnBPJSFktp.setPreferredSize(new java.awt.Dimension(200, 90));
        btnBPJSFktp.setVerifyInputWhenFocusTarget(false);
        btnBPJSFktp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBPJSFktp.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBPJSFktp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBPJSFktpActionPerformed(evt);
            }
        });
        panel2.add(btnBPJSFktp);
        btnBPJSFktp.setBounds(160, 230, 500, 50);

        btnBPJSChekIn.setBackground(new java.awt.Color(255, 0, 204));
        btnBPJSChekIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.black, java.awt.Color.black));
        btnBPJSChekIn.setForeground(new java.awt.Color(0, 0, 0));
        btnBPJSChekIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/gnome-searchtool.png"))); // NOI18N
        btnBPJSChekIn.setText("Chek In Mobile JKN");
        btnBPJSChekIn.setDefaultCapable(false);
        btnBPJSChekIn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBPJSChekIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBPJSChekIn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBPJSChekIn.setIconTextGap(10);
        btnBPJSChekIn.setOpaque(true);
        btnBPJSChekIn.setPreferredSize(new java.awt.Dimension(200, 90));
        btnBPJSChekIn.setVerifyInputWhenFocusTarget(false);
        btnBPJSChekIn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBPJSChekIn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnBPJSChekIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBPJSChekInActionPerformed(evt);
            }
        });
        panel2.add(btnBPJSChekIn);
        btnBPJSChekIn.setBounds(160, 300, 500, 50);

        panel1.add(panel2, java.awt.BorderLayout.CENTER);
        panel2.getAccessibleContext().setAccessibleDescription("");

        panel3.setBackground(new java.awt.Color(153, 153, 153));
        panel3.setName(""); // NOI18N
        panel3.setPreferredSize(new java.awt.Dimension(500, 20));
        panel3.setLayout(new java.awt.BorderLayout());

        LabelNomor.setBackground(new java.awt.Color(153, 153, 153));
        LabelNomor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true), "::[ Nomor Antrian Loket Pendaftaran ]::", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        LabelNomor.setForeground(new java.awt.Color(255, 0, 0));
        LabelNomor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomor.setText("001");
        LabelNomor.setFont(new java.awt.Font("Tahoma", 0, 150)); // NOI18N
        LabelNomor.setOpaque(true);
        LabelNomor.setPreferredSize(new java.awt.Dimension(474, 324));
        panel3.add(LabelNomor, java.awt.BorderLayout.CENTER);

        panel1.add(panel3, java.awt.BorderLayout.EAST);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      //  TCari.setText("");
    }//GEN-LAST:event_formWindowActivated

    private void btnDaftarPoliklinikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarPoliklinikActionPerformed
        //DlgCekNoRM pilih = new DlgCekNoRM(null, true);
        HalamanDua pilih = new HalamanDua (null, true);
        //pilih.setSize(this.getWidth()-20,this.getHeight()-70);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnDaftarPoliklinikActionPerformed

    private void btnPengunjungBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengunjungBaruActionPerformed
        if(Sequel.menyimpantf("antriloketcetak","current_date(),current_time(),'"+LabelNomor.getText()+"'","Nomor Antrian")==true){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Map<String, Object> param = new HashMap<>();
            param.put("namars",akses.getnamars());
            param.put("alamatrs",akses.getalamatrs());
            param.put("kotars",akses.getkabupatenrs());
            param.put("propinsirs",akses.getpropinsirs());
            param.put("kontakrs",akses.getkontakrs());
            param.put("emailrs",akses.getemailrs());
            Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                "select date_format(antriloketcetak.tanggal,'%d-%m-%Y') as tanggal,antriloketcetak.nomor,antriloketcetak.jam from antriloketcetak where antriloketcetak.tanggal=current_date and antriloketcetak.nomor='"+LabelNomor.getText()+"' ",param);
            this.setCursor(Cursor.getDefaultCursor());
            autonomer();
        }else{
            autonomer();
            if(Sequel.menyimpantf("antriloketcetak","current_date(),current_time(),'"+LabelNomor.getText()+"'","Nomor Antrian")==true){
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                Map<String, Object> param = new HashMap<>();
                param.put("namars",akses.getnamars());
                param.put("alamatrs",akses.getalamatrs());
                param.put("kotars",akses.getkabupatenrs());
                param.put("propinsirs",akses.getpropinsirs());
                param.put("kontakrs",akses.getkontakrs());
                param.put("emailrs",akses.getemailrs());
                Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                    "select date_format(antriloketcetak.tanggal,'%d-%m-%Y') as tanggal,antriloketcetak.nomor,antriloketcetak.jam from antriloketcetak where antriloketcetak.tanggal=current_date and antriloketcetak.nomor='"+LabelNomor.getText()+"' ",param);
                this.setCursor(Cursor.getDefaultCursor());
                autonomer();
            }else{
                autonomer();
                if(Sequel.menyimpantf("antriloketcetak","current_date(),current_time(),'"+LabelNomor.getText()+"'","Nomor Antrian")==true){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                        "select date_format(antriloketcetak.tanggal,'%d-%m-%Y') as tanggal,antriloketcetak.nomor,antriloketcetak.jam from antriloketcetak where antriloketcetak.tanggal=current_date and antriloketcetak.nomor='"+LabelNomor.getText()+"' ",param);
                    this.setCursor(Cursor.getDefaultCursor());
                    autonomer();
                }
            }
        }



//        DlgAntrian pilih = new DlgAntrian(null, true);
//        //pilih.setSize(this.getWidth(), this.getHeight());
//        pilih.setSize(this.getWidth()-20,this.getHeight()-70);
//        pilih.setLocationRelativeTo(this);
//        pilih.setVisible(true);
    }//GEN-LAST:event_btnPengunjungBaruActionPerformed

    private void btnDaftarBpjsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarBpjsActionPerformed
        DlgCekSKDP pilih = new DlgCekSKDP (null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        //pilih.setSize(this.getWidth()-20,this.getHeight()-70);
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnDaftarBpjsActionPerformed

    private void btnBPJSFktpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBPJSFktpActionPerformed
        DlgRujukFKTP pilih = new DlgRujukFKTP (null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnBPJSFktpActionPerformed

    private void btnBPJSChekInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBPJSChekInActionPerformed
        DlgBpjsChek pilih = new DlgBpjsChek(null, true);
        pilih.setSize(this.getWidth(), this.getHeight());
        pilih.setLocationRelativeTo(this);
        pilih.setVisible(true);
    }//GEN-LAST:event_btnBPJSChekInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new HalamanDepan().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Label LabelNomor;
    private widget.ButtonBig btnBPJSChekIn;
    private widget.ButtonBig btnBPJSFktp;
    private widget.ButtonBig btnDaftarBpjs;
    private widget.ButtonBig btnDaftarPoliklinik;
    private widget.ButtonBig btnPengunjungBaru;
    private component.Label jLabel1;
    private component.Label jLabel3;
    private component.Panel jPanel1;
    private component.Panel jPanel3;
    private usu.widget.glass.PanelGlass panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables

    private void autonomer(){
        Valid.autoNomer3("select ifnull(MAX(CONVERT(antriloketcetak.nomor,signed)),0) from antriloketcetak where antriloketcetak.tanggal=current_date()","",3,LabelNomor);
    }   

}
