/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package antrian;

//import custom.*;
//import bpjsvclaim.BPJSApi;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.akses;
import simrskhanza.*;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import inventory.DlgCariKonversi;
import inventory.DlgCariObat;
import inventory.DlgCariObat2;
import inventory.DlgCariObat3;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Properties;
import javax.swing.Timer;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author perpustakaan
 */
public class DlgCallerAntrianRegistrationOld extends javax.swing.JDialog {
  private sekuel Sequel=new sekuel();
  private validasi Valid=new validasi();
  private Connection koneksi=koneksiDB.condb();
  public static int LoketClient;
  private int i=0;
  private static final Properties LoketId = new Properties(); 

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public DlgCallerAntrianRegistrationOld(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jSisa.setText(Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='loket' and client='"+CmbLoket.getSelectedItem().toString()+"' and status='Pending' "));
        jNoAntrian.setText(Sequel.cariIsi("SELECT queue_number FROM tt_queue WHERE type='loket' and client='"+CmbLoket.getSelectedItem().toString()+"' and status='Closed' ORDER BY id DESC LIMIT 1 "));

        this.setLocation(8,1);
        setSize(885,350);
        try {
            LoketId.loadFromXML(new FileInputStream("setting/loketid.xml"));
        } catch (Exception e) {
            System.out.println("Notif Setting : "+e);
        }
        LoketClient = Integer.parseInt(LoketId.getProperty("LOKETID"));
        CmbLoket.setSelectedIndex(LoketClient-1);
        
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        FormInput1 = new widget.PanelBiasa();
        jNoAntrian = new widget.Label();
        BtnKeluar2 = new widget.Button();
        BtnKeluar3 = new widget.Button();
        FormInput2 = new widget.PanelBiasa();
        jSisa = new widget.Label();
        CmbLoket = new widget.ComboBox();
        jLabel13 = new widget.Label();
        BtnKeluar4 = new widget.Button();
        panelGlass8 = new widget.panelisi();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "::[ Caller Antrian Registrasi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(70, 70, 70))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(875, 200));
        internalFrame1.setWarnaAtas(new java.awt.Color(204, 255, 255));
        internalFrame1.setWarnaBawah(new java.awt.Color(204, 255, 255));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput.setWarnaAtas(new java.awt.Color(204, 255, 255));
        FormInput.setLayout(null);

        FormInput1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "No. Antrian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        FormInput1.setName("FormInput1"); // NOI18N
        FormInput1.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput1.setWarnaAtas(new java.awt.Color(0, 153, 153));
        FormInput1.setLayout(null);

        jNoAntrian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNoAntrian.setText("A999");
        jNoAntrian.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jNoAntrian.setName("jNoAntrian"); // NOI18N
        FormInput1.add(jNoAntrian);
        jNoAntrian.setBounds(15, 20, 370, 110);

        FormInput.add(FormInput1);
        FormInput1.setBounds(10, 10, 400, 150);

        BtnKeluar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/TestTubes.png"))); // NOI18N
        BtnKeluar2.setMnemonic('T');
        BtnKeluar2.setText("RESET ANTRIAN");
        BtnKeluar2.setToolTipText("Alt+T");
        BtnKeluar2.setName("BtnKeluar2"); // NOI18N
        BtnKeluar2.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar2ActionPerformed(evt);
            }
        });
        BtnKeluar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluar2KeyPressed(evt);
            }
        });
        FormInput.add(BtnKeluar2);
        BtnKeluar2.setBounds(660, 160, 140, 30);

        BtnKeluar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/42a.png"))); // NOI18N
        BtnKeluar3.setMnemonic('T');
        BtnKeluar3.setText("Re-Called ");
        BtnKeluar3.setToolTipText("Alt+T");
        BtnKeluar3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnKeluar3.setGlassColor(new java.awt.Color(204, 51, 255));
        BtnKeluar3.setName("BtnKeluar3"); // NOI18N
        BtnKeluar3.setPreferredSize(new java.awt.Dimension(200, 30));
        BtnKeluar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar3ActionPerformed(evt);
            }
        });
        BtnKeluar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluar3KeyPressed(evt);
            }
        });
        FormInput.add(BtnKeluar3);
        BtnKeluar3.setBounds(410, 170, 210, 40);

        FormInput2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sisa Antrian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        FormInput2.setName("FormInput2"); // NOI18N
        FormInput2.setPreferredSize(new java.awt.Dimension(865, 137));
        FormInput2.setWarnaAtas(new java.awt.Color(0, 153, 153));
        FormInput2.setLayout(null);

        jSisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSisa.setText("-");
        jSisa.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        jSisa.setName("jSisa"); // NOI18N
        FormInput2.add(jSisa);
        jSisa.setBounds(15, 20, 370, 110);

        FormInput.add(FormInput2);
        FormInput2.setBounds(420, 10, 390, 150);

        CmbLoket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        CmbLoket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CmbLoket.setName("CmbLoket"); // NOI18N
        CmbLoket.setPreferredSize(new java.awt.Dimension(50, 30));
        CmbLoket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbLoketItemStateChanged(evt);
            }
        });
        CmbLoket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbLoketKeyPressed(evt);
            }
        });
        FormInput.add(CmbLoket);
        CmbLoket.setBounds(80, 165, 62, 23);

        jLabel13.setText("Loket :");
        jLabel13.setName("jLabel13"); // NOI18N
        FormInput.add(jLabel13);
        jLabel13.setBounds(0, 165, 70, 23);

        BtnKeluar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/History.png"))); // NOI18N
        BtnKeluar4.setMnemonic('T');
        BtnKeluar4.setText("Called");
        BtnKeluar4.setToolTipText("Alt+T");
        BtnKeluar4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnKeluar4.setGlassColor(new java.awt.Color(153, 255, 153));
        BtnKeluar4.setName("BtnKeluar4"); // NOI18N
        BtnKeluar4.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar4ActionPerformed(evt);
            }
        });
        BtnKeluar4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluar4KeyPressed(evt);
            }
        });
        FormInput.add(BtnKeluar4);
        BtnKeluar4.setBounds(230, 170, 170, 40);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(100, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void berhasilSimpan() {  
   
} 
    
    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
    }//GEN-LAST:event_formWindowActivated

    private void BtnKeluar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar2ActionPerformed
 i=JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mereset antrian dari 0 kembali ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
                                if(i==JOptionPane.YES_OPTION){
                                    Sequel.queryu2("update tt_queue set status='pending' where type='loket'");
                                     jSisa.setText(Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='loket'  and status='Pending' "));
                                     jNoAntrian.setText(Sequel.cariIsi("SELECT queue_number FROM tt_queue WHERE type='loket'  and status='Closed' ORDER BY id DESC LIMIT 1 "));
                                }else{                                
                                   
                                }
                               
    
        
       
    }//GEN-LAST:event_BtnKeluar2ActionPerformed

    private void BtnKeluar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluar2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar2KeyPressed

    private void BtnKeluar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar3ActionPerformed
        Sequel.queryu2("update tt_queue set status='open' WHERE queue_number='"+jNoAntrian.getText()+"'");
        //jNoAntrian.setText(Sequel.cariIsi("SELECT queue_number FROM tt_queue WHERE type='loket' and client='"+CmbLoket.getSelectedItem().toString()+"' and status='Closed' ORDER BY id DESC LIMIT 1 "));
           // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar3ActionPerformed

    private void BtnKeluar3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluar3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar3KeyPressed

    private void CmbLoketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbLoketKeyPressed
      
    }//GEN-LAST:event_CmbLoketKeyPressed

    private void CmbLoketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbLoketItemStateChanged
jSisa.setText(Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='loket'  and status='Pending' "));
        jNoAntrian.setText(Sequel.cariIsi("SELECT queue_number FROM tt_queue WHERE type='loket'  and status='Closed' ORDER BY id DESC LIMIT 1 "));
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbLoketItemStateChanged

    private void BtnKeluar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar4ActionPerformed
       // update tt_queue set status='open' WHERE type='loket' and client='1' and status='pending' ORDER BY id ASC LIMIT 1
       String sisa = Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='loket' and status='Pending' ");
       if(sisa.equals("0")){
            JOptionPane.showMessageDialog(null,"Maaf, data Antrian sudah habis.");
                  
       }else{
           Sequel.queryu2("update tt_queue set status='open',client='"+CmbLoket.getSelectedItem().toString()+"' where type='loket' and status='pending' ORDER BY id ASC LIMIT 1");
        jSisa.setText(Sequel.cariIsi("SELECT count(client) FROM tt_queue WHERE type='loket' and status='Pending' "));
        jNoAntrian.setText(Sequel.cariIsi("SELECT queue_number FROM tt_queue WHERE type='loket'  and status='Open' ORDER BY id DESC LIMIT 1 "));
       }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar4ActionPerformed

    private void BtnKeluar4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluar4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar4KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgCallerAntrianRegistrationOld dialog = new DlgCallerAntrianRegistrationOld(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnKeluar2;
    private widget.Button BtnKeluar3;
    private widget.Button BtnKeluar4;
    private widget.ComboBox CmbLoket;
    private widget.PanelBiasa FormInput;
    private widget.PanelBiasa FormInput1;
    private widget.PanelBiasa FormInput2;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel13;
    private widget.Label jNoAntrian;
    private widget.Label jSisa;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
//        Sequel.cariIsi("select nm_pasien from pasien where no_rkm_medis=? ",TPasien,TNoRM.getText());
    }

   

}
